spring:
  application:
    name: UserFeedback
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: error